notes_app/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path
from decouple import config
from notes import views
from notes_app import settings

urlpatterns = [
    path(config('ADMIN_SITE_URL'), admin.site.urls),

    path('', views.index, name='index'),

    # Auth
    path('signup/', views.signupuser, name='signupuser'),
    path('login/', views.loginuser, name='loginuser'),
    path('logout/', views.logoutuser, name='logoutuser'),
    
    # Notes
    path('new/', views.newnote, name='newnote'),
    path('viewnotes/', views.viewnotes, name='mynotes'),
    path('viewnote/<int:id>', views.viewnote, name='viewnote'),
    path('deletenote/<int:id>', views.deletenote, name='deletenote'),
]


notes/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.fields import DateTimeField
from django.urls import reverse

# Create your models here.
class Note(models.Model):
    title = models.CharField(max_length=150)
    content = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now_add=True)
    deleted = models.BooleanField(default=False)
    date_deleted = models.DateTimeField(null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    class Meta:
        verbose_name = ("Note")
        verbose_name_plural = ("Notes")

    def __str__(self):
        return self.title

notes/forms.py
from django import forms
from .models import Note

class NoteForm(forms.ModelForm):
    
    class Meta:
        model = Note
        fields = ("title", "content")

notes/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.contrib.auth import login, logout, authenticate
from notes.forms import NoteForm
from notes.models import Note
# from datetime import datetime
from django.utils import timezone
from django.contrib.auth.decorators import login_required


# Create your views here.
def index(request):
    return render(request, 'notes/index.html', {'title': 'NotesLab'})

def signupuser(request):
    if request.method == 'GET':
        return render(request, 'notes/signup.html', {'title': 'NotesLab | Sign Up', 'form': UserCreationForm()})
    else:
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(username=request.POST['username'], password=request.POST['password1'])
                user.save()
                login(request, user)
                return redirect('mynotes')
            except IntegrityError:
                return render(request, 'notes/signup.html', {'title': 'NotesLab | Sign Up', 'form': UserCreationForm(), 'error': 'This username is taken. Please try another one'})
        else:
            return render(request, 'notes/signup.html', {'title': 'NotesLab | Sign Up', 'form': UserCreationForm(), 'error': 'Passwords do not match'})

def loginuser(request):
    if request.method == 'GET':
        return render(request, "notes/login.html", {'title': 'NotesLab | Login', 'form':AuthenticationForm()})
    else:
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            return render(request, "notes/login.html", {'title': 'NotesLab | Login', 'form':AuthenticationForm(), "error":"Username and password did not match"})
        else:
            login(request, user)
            return redirect('mynotes')

@login_required
def logoutuser(request):
    if request.method == 'POST':
        logout(request)
        return redirect('index')

@login_required
def newnote(request):
    if request.method == 'GET':
        return render(request, 'notes/newnote.html', {'title': 'New Note', 'form': NoteForm()})
    else:
        try:
            form = NoteForm(request.POST)
            new_note = form.save(commit=False)
            new_note.user = request.user
            new_note.save()
            return redirect('mynotes')
        except ValueError:
            return render(request, 'notes/newnote.html', {'title': 'New Note', 'form': NoteForm(), 'error': 'Bad data passed in. Try again.'})

@login_required
def viewnotes(request):
    notes = Note.objects.filter(user=request.user, deleted=False).order_by('-modified')
    return render(request, 'notes/viewnotes.html', {'title': 'My Notes', 'notes': notes})

@login_required
def viewnote(request, id):
    note = get_object_or_404(Note, pk=id)
    if request.user != note.user:
        return redirect('index')
    if request.method == 'GET':
        form = NoteForm(instance=note)
        return render(request, 'notes/viewnote.html', {'title': note.title,'note':note, 'form':form})
    else:
        try:
            form = NoteForm(request.POST, instance=note)
            note.modified = timezone.now()
            form.save()
            return redirect('mynotes')
        except ValueError:
            return render(request, 'notes/viewnote.html', {'title': note.title,'form':NoteForm(), 'error':'Bad info'})

@login_required
def deletenote(request, id):
    note = get_object_or_404(Note, pk=id)
    if request.user != note.user:
        return redirect('index')
    note.deleted = True
    note.date_deleted = timezone.now()
    note.save()
    return redirect('mynotes')

templates/notes/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    {% if not user.is_authenticated or request.path == '/' %}
    <link rel="stylesheet" href="{% static 'css/styles-index.css' %}" />
    {% endif %}
    <title>{{ title }}</title>
</head>
<body>
    {% if user.is_authenticated %}
    <div class="logout-text">
    <a href="#" onclick="$('#signOutBtn').click()" class="nav-link">Logout</a>
    <form style='display: none;' method="POST" action="{% url 'logoutuser' %}">
        {% csrf_token %}
        <button id="signOutBtn" type="submit">Logout</button>
    </form>
    </div>
    {% endif %}
    <div class="container text-center">
        {% block content %}{% endblock content %}
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

</body>
</html>

templates/notes/index.html
{% extends 'notes/base.html' %}

{% block content %}
<main role="main" class="inner cover">
<h1>NotesLab</h1>
<h2>Keep your notes & thoughts here...</h2>
{% if not user.is_authenticated %}
<a id="#signup" class="btn btn-primary" href="{% url 'signupuser' %}" role="button">Sign Up</a>
<a id="#login" class="btn btn-secondary" href="{% url 'loginuser' %}" role="button">Login</a>
{% else %}
<a id="#mynotes" class="btn btn-secondary" href="{% url 'mynotes' %}" role="button">My Notes</a>
{% endif %}
</main>
{% endblock content %}

templates/notes/login.html
{% extends 'notes/base.html' %}

{% block content %}
<h1>NotesLab</h1>
<form method="POST" class="form-signin">
{% csrf_token %}
<label for="inputUsername" class="sr-only">Username</label>
<input type="text" name="username" id="inputUsername" class="form-control" placeholder="Username" required autofocus>
<label for="inputPassword" class="sr-only">Password</label>
<input type="password" name="password" id="inputPassword" class="form-control" placeholder="Password" required>
{% comment %} <div class="checkbox mb-3">
<label>
    <input type="checkbox" value="remember-me"> Remember me
</label>
</div> {% endcomment %}
{% if error %}
<p class="text-danger">{{ error }}</p>
{% endif %}
<button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
<p>Don't have an account yet? <a href="{% url 'signupuser' %}">Sign Up</a></p>
<p class="mt-5 mb-3 text-muted">&copy; 2021</p>
</form>
{% endblock content %}

templates/notes/newnote.html
{% extends 'notes/base.html' %}

{% block content %}
{% if error %}
<div class="alert alert-danger" role="alert">
    {{ error }}
</div>
{% endif %}
<form method='POST' class='form-viewnote'>
{% csrf_token %}
<div class="form-group">
<label for="id_title" class="sr-only">Title</label>
<input type="text" name="title" maxlength="150" required id="id_title" placeholder="Title...">
</div>
<div class="form-group">
<label for="id_content" class="sr-only">Content</label>
<textarea name="content" cols="40" rows="10" id="id_content" placeholder="Type something here..."></textarea>
</div>
<button type="submit" class="btn text-primary">Save</button>
</form>
{% endblock content %}

templates/notes/signup.html
{% extends 'notes/base.html' %}

{% block content %}
<h1>NotesLab</h1>
<form method="POST" class="form-signin">
{% csrf_token %}
<label for="inputUsername" class="sr-only">Username</label>
<input type="text" name="username" id="inputUsername" class="form-control" placeholder="Username" required autofocus>
<label for="inputPassword1" class="sr-only">Password</label>
<input type="password" name="password1" id="inputPassword1" class="form-control" placeholder="Password" required>
<label for="inputPassword2" class="sr-only">Password</label>
<input type="password" name="password2" id="inputPassword2" class="form-control" placeholder="Confirm Password" required>
{% if error %}
<p class="text-danger">{{ error }}</p>
{% endif %}
<button class="btn btn-lg btn-primary btn-block" type="submit">Sign Up</button>
<p>Already have an account? <a href="{% url 'loginuser' %}">Login</a></p>
<p class="mt-5 mb-3 text-muted">&copy; 2021</p>
</form>
{% endblock content %}

templates/notes/viewnote.html
{% extends 'notes/base.html' %}

{% block content %}
<form method="POST" class="form-viewnote">
{% csrf_token %}
<input type="text" name="title" maxlength="150" required id="id_title" value="{{note.title}}">
<div>
<textarea name="content" cols="150" rows="40" id="id_content">
{{note.content}}
</textarea>
</div>
<button type="submit" class="btn text-primary">Save</button>
</form>
{% endblock content %}

templates/notes/viewnotes.html
{% extends 'notes/base.html' %}

{% block content %}
<div class="add-note">
<a href={% url 'newnote' %} class="btn btn-outline-light"><i class="fa fa-plus" aria-hidden="true"></i></a>
</div>
<h1>My Notes ({{ notes.count }})</h1>
<div class="row viewnotes">
{% for note in notes %}
<div class="col-md-3 mr-5 mb-2">
<div class="card text-dark mb-2" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">{{note.title}}</h5>
    {% if note.content %}
    <p class="card-text">{{ note.content | truncatechars:20 }}</p>
    <p class="text-muted">{{note.modified}}</p>
    {% endif %}
    <a href="{% url 'viewnote' note.id %}" class="card-link">Open</a>
    <a href="{% url 'deletenote' note.id %}" class="card-link">Delete</a>
  </div>
</div>
</div>
{% endfor %}
</div>
{% endblock content %}